### ISSUE TITLE
installation [Core 1.4.0] error

### ISSUE THREAD

**Issue by craigh** [Portugao/Image#112]
If I **install**, then **uninstall** then **install** again I get this error:

> Warning: mkdir(): File exists
> Initialization of MUImage failed!

This means that MUImage is not "cleaning up" after itself in the uninstall or it is not properly checking to see if the directory already exists before installing.

**Comment by rallek** [comment]
I tried with current 1.4.0 and it is not able to be installed. 

Error message:
An error was encountered while creating the tables for the MUImage extension. Please enable the development mode by editing the /config/config.php file in order to reveal the error details.Initialization of MUImage failed!

**Comment by rallek** [comment]
aditional info: three tables are available in he database

**Comment by Portugao** [comment]
That is not amusing. Normally it should work, because 1.3.x modules hat to be compatible with 1.4.x?!

**Comment by rallek** [comment]
there is a pagebreak issue I have heared about. But this installation problem seems to be somethimg different.

**Comment by rallek** [comment]
I switched the developer mode on and get these Error message:

Doctrine Exception: Schema-Tool failed with Error 'An exception occurred while executing 'ALTER TABLE muimage_album ADD CONSTRAINT FK_BF185140727ACA70 FOREIGN KEY (parent_id) REFERENCES muimage_album (id)': SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint' while executing DDL: ALTER TABLE muimage_album ADD CONSTRAINT FK_BF185140727ACA70 FOREIGN KEY (parent_id) REFERENCES muimage_album (id)


The table do have no rows inside.

**Comment by craigh** [comment]
per @Guite - modules that are generated for 1.3 with MOST are incompatible with 1.4. changing the `core_max` is not allowed for generated modules. If you want it to work with 1.4, then it must be regenerated for 1.4.

**Comment by rallek** [comment]
or the module fix the paginator issue described here: https://github.com/zikula/core/issues/2329

**Comment by rallek** [comment]
I would be happy to get a patch to make the current version ready for 1.4. Unfortunately I am not able to create it myself.

**Comment by Portugao** [comment]
I can imagine that you would be happy to have a patch.
But a compatible version of MUImage for ZIK 1.4.0 will be the version 1.4.0.
See the label of this issue.

**Comment by rallek** [comment]
I have seen the label and I am running a site with 1.4.0. That is the reason for asking. As Axel is telling at https://github.com/zikula/core/issues/2329 it should be only a little thing. But for me it is to big.

**Comment by Portugao** [comment]
I cannot see that it is a small thing to regenerate, so i will do that for the next main version and that will be MUImage 1.4.0.
If I understand correctly, a regenerated version will not work among 1.3.x, so i have to differentiate the versions for ZIK 1.3.x and ZIK 1.4.x.

**Comment by rallek** [comment]
To regenerate is a different story. There is an issue with pagination. Only the patch for this little boring thing would be great.

**Comment by Guite** [comment]
Well, the difference is that 1.3.x and 1.4 use different Doctrine versions.

In 1.3.x MOST modules use a paginator from Doctrine Extensions, while in 1.4 a paginator from the newer Doctrine versions itself is used.

See here:
https://github.com/Guite/MostGenerator/blob/master/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/models/Repository.xtend#L203
https://github.com/Guite/MostGenerator/blob/master/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/models/Repository.xtend#L732

The only way to solve this in a way that a module can work in both 1.3 and 1.4 is outsourcing these code parts completely into two different classes (like `MyPaginator` and `MyLegacyPaginator`) and call one of them based on the current core version.

**Comment by rallek** [comment]
A documented example implementation would be great.

**Comment by Guite** [comment]
Untested skeleton:

modules/MUImage/lib/MUImage/Paginator/Paginator.php:
```
use Doctrine\ORM\Query;
use Doctrine\ORM\Tools\Pagination\Paginator;

class MUImage_Paginator_Paginator {

    private $query;
    private $hasRelationships;

    public function __construct(Query $query, $hasRelationships)
    {
        $this->query = $query;
        $this->hasRelationships = $hasRelationships;
    }

    public function getResults()
    {
        $paginator = new Paginator($this->query, $this->hasRelationships);
        $count = count($paginator);

        return array($paginator, $count);
    }
}
```

modules/MUImage/lib/MUImage/Paginator/LegacyPaginator.php:
```
use Doctrine\ORM\Query;
use DoctrineExtensions\Paginate\Paginate;

class MUImage_Paginator_LegacyPaginator {

    private $query;
    private $hasRelationships;

    public function __construct(Query $query, $hasRelationships)
    {
        $this->query = $query;
        $this->hasRelationships = $hasRelationships;
    }

    public function getResults($offset, $resultsPerPage)
    {
        // count the total number of affected items
        $count = Paginate::getTotalQueryResults($this->query);
        if ($this->hasRelationships) {
             // prefetch unique relationship ids for given pagination frame
             $this->query = Paginate::getPaginateQuery($this->query, $offset, $resultsPerPage);
        }

        return array($this->query, $count);
    }
}

```

Repository classes (method `getSelectWherePaginatedQuery`):
```
            $paginatorClass = 'MUImage_Paginator_Paginator';

            if ($isLegacy) {
                $result = $query->getResult();
            } else {
                if (!$isPaginated) {
                    $result = $query->getResult();
                } else {
                    $hasRelationships = false/true; // adjust depending on your entity
                    $paginator = new $paginatorClass($query, $hasRelationships);
                    list($result, $count) = $paginator->getResults();
                }
            }
            // ...
```

Repository classes (method `retrieveCollectionResult`):
```
            $qb = $this->addCommonViewFilters($qb);

            $query = $this->getQueryFromBuilder($qb);
            $offset = ($currentPage-1) * $resultsPerPage;

            $isLegacy = version_compare(\Zikula_Core::VERSION_NUM, '1.4.0') >= 0 ? false : true;
            $paginatorClass = 'MUImage_Paginator_' . (!$isLegacy ? 'Paginator' : 'LegacyPaginator');

            if ($isLegacy) {
                $hasRelationships = false/true; // adjust depending on your entity
                $paginator = new $paginatorClass($query, $hasRelationships);
                list($query, $count) = $paginator->getResults($offset, $resultsPerPage);
                if (!$hasRelationships) {
                    $query->setFirstResult($offset)
                          ->setMaxResults($resultsPerPage);
                }
            } else {
                $query->setFirstResult($offset)
                      ->setMaxResults($resultsPerPage);
                $count = 0;
            }
```

**Comment by rallek** [comment]
@Portugao : will you try to implement? For me it is to hard...

**Comment by Portugao** [comment]
In version 1.4.0 it will be get fixed automatically regenerating with MOST.
And before i will do this i need a final version of the core regarding the existing classes.

**Comment by espaan** [comment]
Hi, this would then also hold for SimpleMedia2 BTW. Interesting. thanks @Guite

**Comment by rallek** [comment]
the new generator should fix this. Thanks to Axel!

**Comment by Portugao** [comment]
This can be closed because the actual repository of branch 1.4.0 is installable.
