### ISSUE TITLE
make the images responsive

### ISSUE THREAD

**Issue by rallek** [Portugao/Image#142]
For a website project I am learning the new possibilities (e.g. html5) at least a little :-)

I found the following for images:
https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-srcset

With this you can specify which sizes picture is delivered in relation to the screen size. Might be good feature in future.

The usage of the browsers is not that big at the moment but increasing: http://caniuse.com/#search=srcset

**Comment by Portugao** [comment]
I will see.
